joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Left arm controller

#joint_1_position_controller:
#    type: effort_controllers/JointPositionController
#    joint: joint_1
#    pid: {p: 11.0, i: 0.5, d: 0.05}
#
#joint_2_position_controller:
#    type: effort_controllers/JointPositionController
#    joint: joint_2
#    pid: {p: 11.0, i: 0.5, d: 0.05}
#
#joint_3_position_controller:
#    type: effort_controllers/JointPositionController
#    joint: joint_3
#    pid: {p: 10, i: 1.0, d: 0}
#
#joint_4_position_controller:
#    type: effort_controllers/JointPositionController
#    joint: joint_4
#    pid: {p: 10, i: 1.0, d: 0}

arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_6
  gains:
    joint_1:
      p: 11
      d: 0.05
      i: 0.5
    joint_2:
      p: 11
      d: 0.05
      i: 0.5
      i_clamp: 1
    joint_3:
      p: 10
      d: 0
      i: 1
      i_clamp: 1
    joint_4:
      p: 10
      d: 0
      i: 1
      i_clamp: 1
#    joint_6:
#      p: 10
#      d: 0
#      i: 1
#      i_clamp: 1

#  state_publish_rate:  25            # Override default
#  action_monitor_rate: 30            # Override default
#  stop_trajectory_duration: 0        # Override default