joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Left arm controller

joint_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_1
    pid: {p: 11, i: 0.05, d: 0.5}

joint_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_2
    pid: {p: 11, i: 0.05, d: 0.5}

joint_3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_3
    pid: {p: 11, i: 0.05, d: 0.5}

#  state_publish_rate:  25            # Override default
#  action_monitor_rate: 30            # Override default
#  stop_trajectory_duration: 0        # Override default
